/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create the single user account. Only allowed while no account exists. */
        post: operations["setupAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What's left to set up after the account exists. */
        get: operations["getOnboarding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create the starter agent with the chosen model. Requires the provider to be configured.
         *     Only allowed once (while no agents exist).
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProviderSettings"];
        /** @description Validate the API key against the provider, then save it (encrypted at rest). */
        put: operations["updateProviderSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markChatRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change an agent's settings. Broadcasts an agent.updated event. */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        User: {
            id: string;
            username: string;
        };
        AuthStatus: {
            /** @description True when no account exists yet */
            setupRequired: boolean;
            /** @description The signed-in user, or null */
            user: components["schemas"]["User"] | null;
        };
        OnboardingState: {
            /** @description An OpenCode Go API key has been saved */
            providerConfigured: boolean;
            starterAgentCreated: boolean;
            /** @description Both steps are done; the app is ready to use */
            completed: boolean;
        };
        CompleteOnboardingRequest: {
            /** @description Model id for the starter agent (from GET /models) */
            model: string;
            /** @description Starter agent name; defaults to "barn" */
            agentName?: string;
        };
        CompleteOnboardingResponse: {
            agent: components["schemas"]["Agent"];
            /** @description The starter agent's DM */
            chatId: string;
        };
        ProviderSettings: {
            /** @enum {string} */
            provider: "opencode-go";
            configured: boolean;
            /** @description Last 4 characters of the saved key, e.g. "…a1b2" */
            keyHint: string | null;
        };
        UpdateProviderSettingsRequest: {
            apiKey: string;
        };
        Agent: {
            id: string;
            name: string;
            model: string;
            /** @description Reply language, or "auto" */
            language: string;
            notifications: boolean;
            /** @enum {string} */
            trustMode: "ask" | "trusted";
            isAdmin: boolean;
            activity: components["schemas"]["AgentActivity"];
            /** Format: date-time */
            createdAt: string;
        };
        UpdateAgentRequest: {
            /** @description Model id from GET /models */
            model?: string;
        };
        AgentActivity: {
            /** @enum {string} */
            state: "idle" | "working";
            /** @description What the agent is doing, e.g. "thinking" or "running npm test" */
            label: string | null;
        };
        ChatMember: {
            agentId: string;
            position: number;
        };
        Chat: {
            id: string;
            /** @enum {string} */
            kind: "dm" | "group";
            /** @description Group name, or the agent's name for DMs */
            name: string;
            /** @description Agent participants (the user is implicit in every chat) */
            members: components["schemas"]["ChatMember"][];
            unreadCount: number;
            lastMessage: components["schemas"]["Message"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        MessageAuthor: {
            /** @enum {string} */
            kind: "user" | "agent" | "system";
            agentId: string | null;
        };
        Message: {
            /** @description ULID; lexicographic order is chronological order */
            id: string;
            chatId: string;
            author: components["schemas"]["MessageAuthor"];
            /** @description Markdown */
            body: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Echo of SendMessageRequest.clientId. Only present on the sendMessage response and the
             *     matching message.created event.
             */
            clientId?: string;
        };
        MessagePage: {
            messages: components["schemas"]["Message"][];
            hasMore: boolean;
        };
        SendMessageRequest: {
            body: string;
            /** @description Client-generated id, echoed back so the sender can reconcile its optimistic message */
            clientId?: string;
        };
        MarkReadRequest: {
            lastMessageId: string;
        };
        Model: {
            id: string;
        };
        WsEvent: components["schemas"]["WsMessageCreated"] | components["schemas"]["WsAgentActivity"] | components["schemas"]["WsChatRead"] | components["schemas"]["WsAgentUpdated"];
        WsMessageCreated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.created";
            message: components["schemas"]["Message"];
        };
        WsAgentActivity: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.activity";
            agentId: string;
            activity: components["schemas"]["AgentActivity"];
        };
        /** @description The user read a chat (possibly from another device); clears its unread count */
        WsChatRead: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.read";
            chatId: string;
            lastMessageId: string;
        };
        /** @description An agent's settings changed */
        WsAgentUpdated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.updated";
            agent: components["schemas"]["Agent"];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ChatId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current auth state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    setupAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created and session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onboarding state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingState"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOnboardingRequest"];
            };
        };
        responses: {
            /** @description Starter agent created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getProviderSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model provider settings (the key itself is never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettings"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateProviderSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderSettingsRequest"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettings"];
                };
            };
            /** @description The provider rejected the key, or the request is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All chats, most recently active first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Return messages older than this message id */
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in chronological order (oldest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    markChatRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Marked as read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description The updated agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models available from the provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
            401: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
}
