/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create the single user account. Only allowed while no account exists. */
        post: operations["setupAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What's left to set up after the account exists. */
        get: operations["getOnboarding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create the starter agent with the chosen model. Requires the provider to be configured.
         *     Only allowed once (while no agents exist).
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProviderSettings"];
        /** @description Validate the API key against the provider, then save it (encrypted at rest). */
        put: operations["updateProviderSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markChatRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change an agent's settings. Broadcasts an agent.updated event. */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/agents/{agentId}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        /** @description The durable memories an agent saved, oldest first. */
        get: operations["listMemories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/memories/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
                memoryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Archive an agent: it stops working and disappears from the app (its DM is hidden). The
         *     last admin agent can't be archived. Broadcasts agent.archived.
         */
        post: operations["archiveAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/sandbox": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        /** @description The agent's computer (Docker sandbox) */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/sandbox/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restart the agent's computer. Running processes stop; files in /home/agent stay. */
        post: operations["restartSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        /** @description The agent's scheduled tasks, oldest first. */
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /** @description Pause or resume a task. */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/push/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The VAPID public key browsers subscribe with. */
        get: operations["getPushConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register this browser for notifications. */
        post: operations["subscribePush"];
        delete: operations["unsubscribePush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The kinds of apps that can be connected, with the fields each needs. */
        get: operations["listConnectorTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectors"];
        put?: never;
        /** @description Connect an account. Credentials are checked with the service before saving. */
        post: operations["createConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteConnector"];
        options?: never;
        head?: never;
        /**
         * @description Rename, replace credentials (empty values keep the saved ones), change config, or set
         *     which agents may use the account.
         */
        patch: operations["updateConnector"];
        trace?: never;
    };
    "/settings/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description Save the user's IANA time zone (the web app sends the browser's). Agents' schedules and
         *     "current time" use it.
         */
        put: operations["setTimezone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Re-run the agent's last turn after a failure, from exactly where it stopped. The result
         *     arrives as usual over the WebSocket.
         */
        post: operations["retryAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Answer a pending prompt (a message with `prompt` set). The answer is stored on the
         *     message (broadcast as message.updated) and delivered to the agent that asked.
         */
        post: operations["answerPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Accept a connection an agent proposed (a prompt of kind connect). barn checks the
         *     credentials with the app, saves the connection with the proposed agents' access, marks
         *     the prompt answered (broadcast as message.updated) and tells the agent. Credentials go
         *     straight to the connection and are never shown to the agent. To decline, answer the
         *     prompt with option 1.
         */
        post: operations["connectPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Add the user's reaction with this emoji, or remove it if it's already there. Broadcasts
         *     message.updated; a new reaction on an agent's message is also delivered to that agent.
         */
        post: operations["toggleReaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Dismiss a pending prompt without answering (broadcast as message.updated). */
        post: operations["dismissPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        User: {
            id: string;
            username: string;
        };
        AuthStatus: {
            /** @description True when no account exists yet */
            setupRequired: boolean;
            /** @description The signed-in user, or null */
            user: components["schemas"]["User"] | null;
        };
        OnboardingState: {
            /** @description An OpenCode Go API key has been saved */
            providerConfigured: boolean;
            starterAgentCreated: boolean;
            /** @description Both steps are done; the app is ready to use */
            completed: boolean;
        };
        CompleteOnboardingRequest: {
            /** @description Model id for the starter agent (from GET /models) */
            model: string;
            /** @description Starter agent name; defaults to "barn" */
            agentName?: string;
        };
        CompleteOnboardingResponse: {
            agent: components["schemas"]["Agent"];
            /** @description The starter agent's DM */
            chatId: string;
        };
        ProviderSettings: {
            /** @enum {string} */
            provider: "opencode-go";
            configured: boolean;
            /** @description Last 4 characters of the saved key, e.g. "…a1b2" */
            keyHint: string | null;
        };
        UpdateProviderSettingsRequest: {
            apiKey: string;
        };
        Agent: {
            id: string;
            name: string;
            /** @description What the agent is for and how it should work (its own system instructions) */
            instructions: string;
            model: string;
            /** @description Reply language, or "auto" */
            language: string;
            notifications: boolean;
            /** @enum {string} */
            trustMode: "ask" | "trusted";
            isAdmin: boolean;
            activity: components["schemas"]["AgentActivity"];
            /** Format: date-time */
            createdAt: string;
        };
        Memory: {
            id: string;
            text: string;
            /** Format: date-time */
            createdAt: string;
        };
        Task: {
            id: string;
            agentId: string;
            name: string;
            /** @description What the agent does when the task fires */
            purpose: string;
            /** @enum {string} */
            kind: "cron" | "once" | "signal";
            /** @description 5-field cron in the user's time zone (kind cron) */
            cron: string | null;
            /**
             * Format: date-time
             * @description When a one-off task runs (kind once)
             */
            at: string | null;
            enabled: boolean;
            /** @description kind signal: the event that runs it, e.g. "slack.app_mention in Slack — work where channel contains alerts" */
            signal: string | null;
            /** Format: date-time */
            nextFireAt: string | null;
            /** Format: date-time */
            lastFiredAt: string | null;
        };
        ConnectorField: {
            key: string;
            label: string;
            help?: string;
            secret: boolean;
            optional: boolean;
        };
        ConnectorSignalType: {
            type: string;
            description: string;
            fields: string[];
        };
        ConnectorType: {
            /** @description Machine name, e.g. "github" */
            type: string;
            /** @description Display name, e.g. "GitHub" */
            name: string;
            description: string;
            credentialFields: components["schemas"]["ConnectorField"][];
            configFields: components["schemas"]["ConnectorField"][];
            signals: components["schemas"]["ConnectorSignalType"][];
            /** @description Receives events at a webhook URL (shown after connecting) */
            webhooks: boolean;
        };
        Connector: {
            id: string;
            type: string;
            name: string;
            config: {
                [key: string]: string;
            };
            /** @description Credential keys that have a saved value (values are never returned) */
            credentialsSet: string[];
            /** @description Agents allowed to use this account */
            agentIds: string[];
            /** @description Where the service should send events (types with webhooks) */
            webhookUrl: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateConnectorRequest: {
            type: string;
            name: string;
            credentials: {
                [key: string]: string;
            };
            config?: {
                [key: string]: string;
            };
            agentIds?: string[];
        };
        UpdateConnectorRequest: {
            name?: string;
            credentials?: {
                [key: string]: string;
            };
            config?: {
                [key: string]: string;
            };
            agentIds?: string[];
        };
        UpdateTaskRequest: {
            enabled: boolean;
        };
        PushConfig: {
            publicKey: string;
        };
        PushSubscription: {
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
        };
        PushUnsubscribe: {
            endpoint: string;
        };
        SetTimezoneRequest: {
            /** @description IANA name, e.g. "America/Montevideo" */
            timezone: string;
        };
        Sandbox: {
            /**
             * @description unavailable: Docker isn't set up on the server; none: not created yet (created on
             *     first use)
             * @enum {string}
             */
            status: "unavailable" | "none" | "stopped" | "running";
            /** @description Other agents using the same computer */
            sharedWith: string[];
        };
        UpdateAgentRequest: {
            /** @description Model id from GET /models */
            model?: string;
            name?: string;
            instructions?: string;
            /** @description "auto" (reply in the language people write in) or a language name */
            language?: string;
            /**
             * @description trusted skips approvals for gated actions
             * @enum {string}
             */
            trustMode?: "ask" | "trusted";
            /** @description Push this agent's messages to the user's devices */
            notifications?: boolean;
        };
        AgentActivity: {
            /** @enum {string} */
            state: "idle" | "working";
            /** @description What the agent is doing, e.g. "thinking" or "running npm test" */
            label: string | null;
        };
        ChatMember: {
            agentId: string;
            position: number;
        };
        Chat: {
            id: string;
            /** @enum {string} */
            kind: "dm" | "group";
            /** @description Group name, or the agent's name for DMs */
            name: string;
            /** @description Agent participants (the user is implicit in every chat) */
            members: components["schemas"]["ChatMember"][];
            unreadCount: number;
            lastMessage: components["schemas"]["Message"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        MessageAuthor: {
            /** @enum {string} */
            kind: "user" | "agent" | "system";
            agentId: string | null;
        };
        Message: {
            /** @description ULID; lexicographic order is chronological order */
            id: string;
            chatId: string;
            author: components["schemas"]["MessageAuthor"];
            /** @description Markdown */
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Set on system messages reporting that an agent's turn failed */
            failure?: components["schemas"]["MessageFailure"] | null;
            /** @description Agents @mentioned in the message (group chats) */
            mentions: string[];
            /** @description Emoji reactions, in the order each emoji was first used */
            reactions: components["schemas"]["Reaction"][];
            /**
             * @description Set on agent messages that ask the user something with clickable answers. `body`
             *     holds the question as plain text (for previews).
             */
            prompt?: components["schemas"]["Prompt"] | null;
            /** @description Set on system messages that mark something that happened, e.g. an agent was created */
            event?: components["schemas"]["MessageEvent"] | null;
            /**
             * @description Echo of SendMessageRequest.clientId. Only present on the sendMessage response and the
             *     matching message.created event.
             */
            clientId?: string;
        };
        MessageFailure: {
            agentId: string;
            /**
             * @description model_blocked: OpenCode refuses the agent's model (its provider trains on request
             *     data and the workspace's privacy settings forbid that). Offer to change the model.
             * @enum {string}
             */
            reason: "no_key" | "invalid_key" | "model_blocked" | "provider_error" | "too_many_steps";
            retryable: boolean;
        };
        ToggleReactionRequest: {
            emoji: string;
        };
        Reaction: {
            emoji: string;
            /** @description Who reacted with this emoji, oldest first */
            by: components["schemas"]["MessageAuthor"][];
        };
        Prompt: {
            /**
             * @description single = pick one; multi = pick any number; text = free-text answer; approval = the
             *     agent wants to do something that needs the user's OK (options: Approve, Decline);
             *     connect = the agent proposes connecting an app (see connection; options: Connect,
             *     Decline; connect with POST /messages/{messageId}/connect)
             * @enum {string}
             */
            kind: "single" | "multi" | "text" | "approval" | "connect";
            question: string;
            options: components["schemas"]["PromptOption"][];
            /** @description Offer "type your own" in addition to the options */
            allowOther: boolean;
            /** @enum {string} */
            status: "pending" | "answered" | "dismissed";
            answer: components["schemas"]["PromptAnswer"] | null;
            /** @description The proposed connection (connect prompts only) */
            connection?: components["schemas"]["PromptConnection"] | null;
        };
        PromptConnection: {
            /** @description Connector type name (see /connectors/types) */
            type: string;
            name: string;
            /** @description Non-secret settings the agent filled in (e.g. the server URL) */
            config: {
                [key: string]: string;
            };
            /** @description Agents that get access once it's connected */
            agentIds: string[];
            /** @description The connection, once the user connected it */
            accountId: string | null;
        };
        ConnectPromptRequest: {
            /** @description Values for the type's credential fields */
            credentials: {
                [key: string]: string;
            };
            /** @description Overrides the proposed name */
            name?: string;
        };
        PromptOption: {
            label: string;
            /** @description Choosing this option also opens this chat (e.g. "Go talk to X") */
            opensChatId?: string;
        };
        PromptAnswer: {
            /** @description Indexes of the chosen options */
            selected?: number[];
            /** @description Free-text answer (text prompts, or "type your own") */
            text?: string;
        };
        MessageEvent: {
            /** @enum {string} */
            kind: "agent_created";
            /** @description The agent the event is about (e.g. the one that was created) */
            agentId: string;
            /** @description A chat to link to (e.g. the new agent's DM) */
            chatId?: string;
        };
        MessagePage: {
            messages: components["schemas"]["Message"][];
            hasMore: boolean;
        };
        SendMessageRequest: {
            body: string;
            /** @description Client-generated id, echoed back so the sender can reconcile its optimistic message */
            clientId?: string;
        };
        MarkReadRequest: {
            lastMessageId: string;
        };
        Model: {
            id: string;
        };
        WsEvent: components["schemas"]["WsMessageCreated"] | components["schemas"]["WsAgentActivity"] | components["schemas"]["WsChatRead"] | components["schemas"]["WsAgentUpdated"] | components["schemas"]["WsMessageUpdated"] | components["schemas"]["WsAgentCreated"] | components["schemas"]["WsChatCreated"] | components["schemas"]["WsAgentArchived"];
        WsMessageCreated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.created";
            message: components["schemas"]["Message"];
        };
        WsAgentActivity: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.activity";
            agentId: string;
            activity: components["schemas"]["AgentActivity"];
        };
        /** @description The user read a chat (possibly from another device); clears its unread count */
        WsChatRead: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.read";
            chatId: string;
            lastMessageId: string;
        };
        /** @description An agent's settings changed */
        WsAgentUpdated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.updated";
            agent: components["schemas"]["Agent"];
        };
        /** @description A message changed (its prompt was answered or dismissed, or it got a reaction) */
        WsMessageUpdated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.updated";
            message: components["schemas"]["Message"];
        };
        WsAgentCreated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.created";
            agent: components["schemas"]["Agent"];
        };
        WsChatCreated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.created";
            chat: components["schemas"]["Chat"];
        };
        /** @description An agent was archived; drop it and its DM from the app */
        WsAgentArchived: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.archived";
            agentId: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ChatId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current auth state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    setupAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created and session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onboarding state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingState"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOnboardingRequest"];
            };
        };
        responses: {
            /** @description Starter agent created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getProviderSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model provider settings (the key itself is never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettings"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateProviderSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderSettingsRequest"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettings"];
                };
            };
            /** @description The provider rejected the key, or the request is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All chats, most recently active first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Return messages older than this message id */
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in chronological order (oldest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    markChatRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Marked as read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description The updated agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listMemories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
                memoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    archiveAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description The agent can't be archived (e.g. it's the only admin agent) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    restartSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox state after the restart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description The updated task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getPushConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Push config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfig"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    subscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscription"];
            };
        };
        responses: {
            /** @description Subscribed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    unsubscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushUnsubscribe"];
            };
        };
        responses: {
            /** @description Unsubscribed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listConnectorTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorType"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connector"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectorRequest"];
            };
        };
        responses: {
            /** @description Connected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connector"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    deleteConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectorRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connector"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    setTimezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTimezoneRequest"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    retryAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description The agent is busy and will pick up pending work on its own */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    answerPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptAnswer"];
            };
        };
        responses: {
            /** @description The updated message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description The prompt was already answered or dismissed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    connectPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectPromptRequest"];
            };
        };
        responses: {
            /** @description The updated message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description The app rejected the details; the prompt stays pending */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description The prompt was already answered or dismissed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description barn couldn't reach the app */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    toggleReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleReactionRequest"];
            };
        };
        responses: {
            /** @description The updated message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    dismissPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description The prompt was already answered or dismissed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models available from the provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
            401: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
}
