/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppChatsChatIdRouteImport } from './routes/_app/chats.$chatId'
import { Route as AppAgentsAgentIdComputerRouteImport } from './routes/_app/agents.$agentId.computer'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdComputerRoute =
  AppAgentsAgentIdComputerRouteImport.update({
    id: '/agents/$agentId/computer',
    path: '/agents/$agentId/computer',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/connectors': typeof AppConnectorsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/agents/$agentId/computer': typeof AppAgentsAgentIdComputerRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/connectors': typeof AppConnectorsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/': typeof AppIndexRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/agents/$agentId/computer': typeof AppAgentsAgentIdComputerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chats/$chatId': typeof AppChatsChatIdRoute
  '/_app/agents/$agentId/computer': typeof AppAgentsAgentIdComputerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/connectors'
    | '/schedule'
    | '/settings'
    | '/skills'
    | '/chats/$chatId'
    | '/agents/$agentId/computer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/connectors'
    | '/schedule'
    | '/settings'
    | '/skills'
    | '/'
    | '/chats/$chatId'
    | '/agents/$agentId/computer'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/connectors'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/'
    | '/_app/chats/$chatId'
    | '/_app/agents/$agentId/computer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/$chatId': {
      id: '/_app/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/computer': {
      id: '/_app/agents/$agentId/computer'
      path: '/agents/$agentId/computer'
      fullPath: '/agents/$agentId/computer'
      preLoaderRoute: typeof AppAgentsAgentIdComputerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute
  AppAgentsAgentIdComputerRoute: typeof AppAgentsAgentIdComputerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectorsRoute: AppConnectorsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsChatIdRoute: AppChatsChatIdRoute,
  AppAgentsAgentIdComputerRoute: AppAgentsAgentIdComputerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
